### ISSUE TITLE
Is there a way to enable support for Amazon's V4 authentication scheme?

### ISSUE THREAD

**Issue by ilyabo** [jamestalmage/s3-static-site-uploader#1]
The newer regions provided for S3 (e.g. Frankfurt = eu-central-1) do not support the old authentication scheme, that is V2. So I get the following error when running s3-upload:

```
{ [InvalidRequest: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.]
  message: 'The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.',
  code: 'InvalidRequest',
  name: 'InvalidRequest',
  statusCode: 400,
  retryable: false }
```

Is there a way to enable V4 aka AWS4-HMAC-SHA256 in s3-uploader?

See also http://stackoverflow.com/questions/26533245

**Comment by jamestalmage** [comment]
@ilyabo Closing this since I think it was resolved along with #2.

If you continue to have problems, let me know.

**Comment by jeremythille** [comment]
Hi, unburying an issue here, but I have exactly the same issue as @ilyabo. I tried the fix you suggest, but there is no such directory as `node_modules/s3_upload`. There is a `node_modules/s3` though. I tried `npm install aws-sdk@2` in it, it installed something, but uploads still fail. I still get this message : 

> unable to upload:
> InvalidRequest: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.

I can find nothing in your doc to enable v4 authentication. My bucket is also in Frankfurt.
